{
   "assignee" : null,
   "body" : "I'm running Ubuntu 11.10 x86_64.  I first started getting this error with the bitcoin-qt in ubuntu's ppa repository, but when I tried the code from this git I get the same issue.\r\n\r\n\r\nxxx@XXX:~/workspace/bitcoin$ ./bitcoin-qt \r\n\r\n(bitcoin-qt:21295): Gtk-WARNING **: Unable to locate theme engine in module_path: \"pixmap\",\r\nterminate called after throwing an instance of 'DbRunRecoveryException'\r\n  what():  DbEnv::txn_checkpoint: DB_RUNRECOVERY: Fatal error, run database recovery\r\nAborted\r\n\r\n\r\nAnd when I run it through gdb I get this:\r\n\r\nxxx@XXX:~/workspace/bitcoin$ gdb ./bitcoin-qt \r\nGNU gdb (Ubuntu/Linaro 7.3-0ubuntu2) 7.3-2011.08\r\nCopyright (C) 2011 Free Software Foundation, Inc.\r\nLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\r\nThis is free software: you are free to change and redistribute it.\r\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\r\nand \"show warranty\" for details.\r\nThis GDB was configured as \"x86_64-linux-gnu\".\r\nFor bug reporting instructions, please see:\r\n<http://bugs.launchpad.net/gdb-linaro/>...\r\nReading symbols from /home/xxx/workspace/bitcoin/bitcoin-qt...(no debugging symbols found)...done.\r\n(gdb) run\r\nStarting program: /home/xxx/workspace/bitcoin/bitcoin-qt \r\n[Thread debugging using libthread_db enabled]\r\n\r\n(bitcoin-qt:21316): Gtk-WARNING **: Unable to locate theme engine in module_path: \"pixmap\",\r\n[New Thread 0x7fffe7ec4700 (LWP 21319)]\r\n[New Thread 0x7fffe74c0700 (LWP 21320)]\r\nterminate called after throwing an instance of 'DbRunRecoveryException'\r\n  what():  DbEnv::txn_checkpoint: DB_RUNRECOVERY: Fatal error, run database recovery\r\n\r\nProgram received signal SIGABRT, Aborted.\r\n0x00007ffff48f53a5 in raise () from /lib/x86_64-linux-gnu/libc.so.6\r\n(gdb) quit\r\nA debugging session is active.\r\n\r\n\tInferior 1 [process 21316] will be killed.\r\n\r\nQuit anyway? (y or n) y\r\n\r\nI tried removing the .bitcoin directory and repopulating, but I still get the error.",
   "closed_at" : "2012-04-12T20:29:30Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/331997?v=3",
      "events_url" : "https://api.github.com/users/gavinandresen/events{/privacy}",
      "followers_url" : "https://api.github.com/users/gavinandresen/followers",
      "following_url" : "https://api.github.com/users/gavinandresen/following{/other_user}",
      "gists_url" : "https://api.github.com/users/gavinandresen/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/gavinandresen",
      "id" : 331997,
      "login" : "gavinandresen",
      "organizations_url" : "https://api.github.com/users/gavinandresen/orgs",
      "received_events_url" : "https://api.github.com/users/gavinandresen/received_events",
      "repos_url" : "https://api.github.com/users/gavinandresen/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/gavinandresen/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/gavinandresen/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/gavinandresen"
   },
   "comments" : 7,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1048/comments",
   "created_at" : "2012-04-05T23:48:42Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1048/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/1048",
   "id" : 3998112,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1048/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 1048,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "terminate called after throwing an instance of 'DbRunRecoveryException'",
   "updated_at" : "2012-04-12T20:29:30Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1048",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/1617090?v=3",
      "events_url" : "https://api.github.com/users/drak01/events{/privacy}",
      "followers_url" : "https://api.github.com/users/drak01/followers",
      "following_url" : "https://api.github.com/users/drak01/following{/other_user}",
      "gists_url" : "https://api.github.com/users/drak01/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/drak01",
      "id" : 1617090,
      "login" : "drak01",
      "organizations_url" : "https://api.github.com/users/drak01/orgs",
      "received_events_url" : "https://api.github.com/users/drak01/received_events",
      "repos_url" : "https://api.github.com/users/drak01/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/drak01/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/drak01/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/drak01"
   }
}
