[
   {
      "body" : "Update with Debug Data\r\n\r\nDesktop #1 Debug data-\r\n2016-05-18 22:58:42 *** System error while flushing: CDB: Error -30974, can't open database \r\n2016-05-18 23:18:38 socket sending timeout: 1201s\r\n2016-05-18 23:18:41 socket sending timeout: 1201s\r\n2016-05-18 23:18:41 socket sending timeout: 1201s\r\n2016-05-18 23:18:41 socket sending timeout: 1201s\r\n2016-05-18 23:18:41 socket sending timeout: 1201s\r\n2016-05-18 23:18:41 socket sending timeout: 1201s\r\n2016-05-19 16:19:19 ERROR: ProcessNewBlock: ActivateBestChain failed\r\n2016-05-19 16:19:19 socket send error An operation was attempted on something that is not a socket.  (10038)\r\n2016-05-19 16:19:19 tor: Thread interrupt\r\n2016-05-19 16:19:19 addcon thread interrupt\r\n2016-05-19 16:19:19 torcontrol thread exit\r\n2016-05-19 16:19:19 opencon thread interrupt\r\n2016-05-19 16:19:19 scheduler thread interrupt\r\n2016-05-19 16:19:19 msghand thread interrupt\r\n2016-05-19 16:19:19 net thread interrupt\r\n2016-05-19 16:19:19 Shutdown: In progress...\r\n2016-05-19 16:19:19 StopNode()\r\n2016-05-19 16:19:19 *** System error while flushing: CDB: Error -30974, can't open database \r\n2016-05-19 16:19:24 CDBEnv::EnvShutdown: Error -30974 shutting down database environment: DB_RUNRECOVERY: Fatal error, run database recovery\r\n2016-05-19 16:19:24 Shutdown: done\r\n\r\n\r\nDesktop #2 Data-\r\n2016-05-18 22:48:40 *** System error while flushing: CDB: Error -30974, can't open database \r\n2016-05-18 23:08:27 ping timeout: 1200.005373s\r\n2016-05-18 23:08:27 ping timeout: 1200.031379s\r\n2016-05-18 23:08:38 socket sending timeout: 1201s\r\n2016-05-18 23:08:38 socket sending timeout: 1201s\r\n2016-05-18 23:08:38 socket sending timeout: 1201s\r\n2016-05-19 16:28:40 ERROR: ProcessNewBlock: ActivateBestChain failed\r\n2016-05-19 16:28:41 tor: Thread interrupt\r\n2016-05-19 16:28:41 torcontrol thread exit\r\n2016-05-19 16:28:41 addcon thread interrupt\r\n2016-05-19 16:28:41 opencon thread interrupt\r\n2016-05-19 16:28:41 msghand thread interrupt\r\n2016-05-19 16:28:41 scheduler thread interrupt\r\n2016-05-19 16:28:41 net thread interrupt\r\n2016-05-19 16:28:41 Shutdown: In progress...\r\n2016-05-19 16:28:41 StopNode()\r\n2016-05-19 16:28:41 *** System error while flushing: CDB: Error -30974, can't open database \r\n2016-05-19 16:28:44 CDBEnv::EnvShutdown: Error -30974 shutting down database environment: DB_RUNRECOVERY: Fatal error, run database recovery\r\n2016-05-19 16:28:44 Shutdown: done\r\n\r\n\r\n\r\n\r\n\r\n",
      "created_at" : "2016-05-19T18:08:20Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8074#issuecomment-220406317",
      "id" : 220406317,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8074",
      "updated_at" : "2016-05-19T18:08:59Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/220406317",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/19475428?v=3",
         "events_url" : "https://api.github.com/users/kcb4348/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kcb4348/followers",
         "following_url" : "https://api.github.com/users/kcb4348/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kcb4348/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kcb4348",
         "id" : 19475428,
         "login" : "kcb4348",
         "organizations_url" : "https://api.github.com/users/kcb4348/orgs",
         "received_events_url" : "https://api.github.com/users/kcb4348/received_events",
         "repos_url" : "https://api.github.com/users/kcb4348/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kcb4348/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kcb4348/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kcb4348"
      }
   },
   {
      "body" : "I would say your `wallet.dat` file is corrupted or you have create the wallet.dat file with a bitcoin-version that was compiled with `--incompatible-bdb` (though not sure if that would rise your particular error).\r\n\r\nYou could analyze your wallet.dat file more deeply. Maybe download some berkley db utilities or use python (http://stackoverflow.com/questions/37644/examining-berkeley-db-files-from-the-cli).",
      "created_at" : "2016-05-19T18:31:16Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8074#issuecomment-220412716",
      "id" : 220412716,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8074",
      "updated_at" : "2016-05-19T18:31:16Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/220412716",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/178464?v=3",
         "events_url" : "https://api.github.com/users/jonasschnelli/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonasschnelli/followers",
         "following_url" : "https://api.github.com/users/jonasschnelli/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonasschnelli",
         "id" : 178464,
         "login" : "jonasschnelli",
         "organizations_url" : "https://api.github.com/users/jonasschnelli/orgs",
         "received_events_url" : "https://api.github.com/users/jonasschnelli/received_events",
         "repos_url" : "https://api.github.com/users/jonasschnelli/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonasschnelli/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonasschnelli"
      }
   },
   {
      "body" : "All three Bitcoin programs I've imaged had the default wallet.dat file.  I was waiting until the program would completely synchronize before updating with my back-up.  I should add that the same thing happens with my back-up in the bitcoin folder.",
      "created_at" : "2016-05-19T21:39:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8074#issuecomment-220459763",
      "id" : 220459763,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8074",
      "updated_at" : "2016-05-19T21:39:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/220459763",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/19475428?v=3",
         "events_url" : "https://api.github.com/users/kcb4348/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kcb4348/followers",
         "following_url" : "https://api.github.com/users/kcb4348/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kcb4348/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kcb4348",
         "id" : 19475428,
         "login" : "kcb4348",
         "organizations_url" : "https://api.github.com/users/kcb4348/orgs",
         "received_events_url" : "https://api.github.com/users/kcb4348/received_events",
         "repos_url" : "https://api.github.com/users/kcb4348/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kcb4348/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kcb4348/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kcb4348"
      }
   },
   {
      "body" : "My mistake - the two desktop Bitcoin programs had the default wallet.dat and the laptop had my wallet.dat back-up.",
      "created_at" : "2016-05-19T22:13:47Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8074#issuecomment-220467135",
      "id" : 220467135,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8074",
      "updated_at" : "2016-05-19T22:13:47Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/220467135",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/19475428?v=3",
         "events_url" : "https://api.github.com/users/kcb4348/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kcb4348/followers",
         "following_url" : "https://api.github.com/users/kcb4348/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kcb4348/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kcb4348",
         "id" : 19475428,
         "login" : "kcb4348",
         "organizations_url" : "https://api.github.com/users/kcb4348/orgs",
         "received_events_url" : "https://api.github.com/users/kcb4348/received_events",
         "repos_url" : "https://api.github.com/users/kcb4348/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kcb4348/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kcb4348/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kcb4348"
      }
   },
   {
      "body" : "Closing, was user's mistake.",
      "created_at" : "2016-11-16T13:21:45Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8074#issuecomment-260944775",
      "id" : 260944775,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8074",
      "updated_at" : "2016-11-16T13:21:45Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/260944775",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   }
]
