{
   "assignee" : null,
   "assignees" : [],
   "body" : "This PR addresses the case where a wallet transaction fails to be accepted to the mempool when committed. This would keep the transaction in the wallet, to be rebroadcast at some undetermined time in the future, with the consequence that the change output would be cloaked. Even adding the mempool transactions into a new block will not immediately resolve the problem, due to the wallet not rebroadcasting the transaction immediately (even to itself) for (I think) privacy reasons.\r\n\r\nAlthough there is a `walletrejectlongchain` option, the behavior when this is turned off is confusing and unpredictable, as noted above, and the `CommitTransaction` code will do the exact same thing for other mempool add failures, whichever those may be.\r\n\r\nEdit: ~~~open question and currently investigating: will the coin selection algorithm inadvertently pick UTXOs that would result in a rejection of the transaction even if the user has other UTXOs available that wouldn't result in a too long chain? I have tried to trigger this case but the coin select is always picking the \"right\" UTXO that won't result in failure.~~~\r\n\r\nEdit 2: In https://github.com/bitcoin/bitcoin/blame/master/src/wallet/wallet.cpp#L2457 the very last attempt to select coins increases the ancestor cap to num max, so above concern about coin select sometimes inadvertently picking an unspendable-due-to-chain-length tx is not a problem.",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 5,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11019/comments",
   "created_at" : "2017-08-10T05:48:17Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11019/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/11019",
   "id" : 249239510,
   "labels" : [
      {
         "color" : "02d7e1",
         "default" : false,
         "id" : 149424,
         "name" : "Wallet",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Wallet"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11019/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 11019,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/11019.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/11019",
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/11019.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/11019"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "title" : "[wallet] Abandon transactions that fail to go into the mempool",
   "updated_at" : "2017-08-10T07:16:47Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11019",
   "user" : {
      "avatar_url" : "https://avatars3.githubusercontent.com/u/250224?v=4",
      "events_url" : "https://api.github.com/users/kallewoof/events{/privacy}",
      "followers_url" : "https://api.github.com/users/kallewoof/followers",
      "following_url" : "https://api.github.com/users/kallewoof/following{/other_user}",
      "gists_url" : "https://api.github.com/users/kallewoof/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/kallewoof",
      "id" : 250224,
      "login" : "kallewoof",
      "organizations_url" : "https://api.github.com/users/kallewoof/orgs",
      "received_events_url" : "https://api.github.com/users/kallewoof/received_events",
      "repos_url" : "https://api.github.com/users/kallewoof/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/kallewoof/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/kallewoof/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/kallewoof"
   }
}
