{
   "assignee" : null,
   "assignees" : [],
   "body" : "After doing a `git clean -dfx` and rebuilding, the python tests started failing:\r\n\r\nTest output:\r\n```\r\nroot@0f51c0a75128:/home/bitcoin/bitcoin# python3 qa/pull-tester/rpc-tests.py receivedby\r\n.\r\nreceivedby.py:\r\n2017-03-15 02:31:58.943000 TestFramework (INFO): Initializing test directory /tmp/testmvbdk1ho/592\r\n2017-03-15 02:31:59.240000 TestFramework (ERROR): Unexpected exception caught during testing\r\nTraceback (most recent call last):\r\n  File \"/home/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py\", line 145, in main\r\n    self.setup_chain()\r\n  File \"/home/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py\", line 49, in setup_chain\r\n    initialize_chain(self.options.tmpdir, self.num_nodes, self.options.cachedir)\r\n  File \"/home/bitcoin/bitcoin/qa/rpc-tests/test_framework/util.py\", line 258, in initialize_chain\r\n    wait_for_bitcoind_start(bitcoind_processes[i], rpc_url(i), i)\r\n  File \"/home/bitcoin/bitcoin/qa/rpc-tests/test_framework/util.py\", line 216, in wait_for_bitcoind_start\r\n    raise Exception('bitcoind exited with status %i during initialization' % process.returncode)\r\nException: bitcoind exited with status 1 during initialization\r\n2017-03-15 02:31:59.264000 TestFramework (INFO): Stopping nodes\r\n\r\nstderr:\r\n: Error opening block database.\r\nPlease restart with -reindex or -reindex-chainstate to recover.\r\nTraceback (most recent call last):\r\n  File \"/home/bitcoin/bitcoin/qa/rpc-tests/receivedby.py\", line 147, in <module>\r\n    ReceivedByTest().main()\r\n  File \"/home/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py\", line 162, in main\r\n    stop_nodes(self.nodes)\r\n  File \"/home/bitcoin/bitcoin/qa/rpc-tests/test_framework/util.py\", line 380, in stop_nodes\r\n    for i, node in enumerate(nodes):\r\nTypeError: 'NoneType' object is not iterable\r\n\r\nPass: False, Duration: 1 s\r\n\r\nTEST          | PASSED | DURATION\r\n\r\nreceivedby.py | False  | 1 s\r\n\r\nALL           | False  | 1 s (accumulated)\r\n\r\nRuntime: 1 s\r\nroot@0f51c0a75128:/home/bitcoin/bitcoin#\r\n```\r\n\r\nDebug Logs:\r\n```\r\n2017-03-15 02:31:59 \r\n2017-03-15 02:31:59 Bitcoin version v0.14.99.0-ce01e62\r\n2017-03-15 02:31:59 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1\r\n2017-03-15 02:31:59 Validating signatures for all blocks.\r\n2017-03-15 02:31:59 Default data directory /root/.bitcoin\r\n2017-03-15 02:31:59 Using data directory /home/bitcoin/bitcoin/qa/cache/node0/regtest\r\n2017-03-15 02:31:59 Using config file /home/bitcoin/bitcoin/qa/cache/node0/bitcoin.conf\r\n2017-03-15 02:31:59 Using at most 125 automatic connections (1048576 file descriptors available)\r\n2017-03-15 02:31:59 Using 32 MiB out of 32 requested for signature cache, able to store 1048576 elements\r\n2017-03-15 02:31:59 Using 4 threads for script verification\r\n2017-03-15 02:31:59 scheduler thread start\r\n2017-03-15 02:31:59 HTTP: creating work queue of depth 16\r\n2017-03-15 02:31:59 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.\r\n2017-03-15 02:31:59 HTTP: starting 4 worker threads\r\n2017-03-15 02:31:59 init message: Verifying wallet...\r\n2017-03-15 02:31:59 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)\r\n2017-03-15 02:31:59 Using wallet wallet.dat\r\n2017-03-15 02:31:59 CDBEnv::Open: LogDir=/home/bitcoin/bitcoin/qa/cache/node0/regtest/database ErrorFile=/home/bitcoin/bitcoin/qa/cache/node0/regtest/db.log\r\n2017-03-15 02:31:59 Bound to [::]:15736\r\n2017-03-15 02:31:59 Bound to 0.0.0.0:15736\r\n2017-03-15 02:31:59 Cache configuration:\r\n2017-03-15 02:31:59 * Using 2.0MiB for block index database\r\n2017-03-15 02:31:59 * Using 8.0MiB for chain state database\r\n2017-03-15 02:31:59 * Using 290.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)\r\n2017-03-15 02:31:59 init message: Loading block index...\r\n2017-03-15 02:31:59 Opening LevelDB in /home/bitcoin/bitcoin/qa/cache/node0/regtest/blocks/index\r\n2017-03-15 02:31:59 IO error: /home/bitcoin/bitcoin/qa/cache/node0/regtest/blocks/index: Invalid argument\r\n2017-03-15 02:31:59 : Error opening block database.\r\nPlease restart with -reindex or -reindex-chainstate to recover.\r\n2017-03-15 02:31:59 Aborted block database rebuild. Exiting.\r\n2017-03-15 02:31:59 Shutdown: In progress...\r\n2017-03-15 02:31:59 scheduler thread interrupt\r\n2017-03-15 02:31:59 Shutdown: done\r\n```\r\n\r\nHas anyone already got something like that ?",
   "closed_at" : "2017-08-24T09:08:28Z",
   "closed_by" : {
      "avatar_url" : "https://avatars0.githubusercontent.com/u/126646?v=4",
      "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
      "followers_url" : "https://api.github.com/users/laanwj/followers",
      "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
      "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/laanwj",
      "id" : 126646,
      "login" : "laanwj",
      "organizations_url" : "https://api.github.com/users/laanwj/orgs",
      "received_events_url" : "https://api.github.com/users/laanwj/received_events",
      "repos_url" : "https://api.github.com/users/laanwj/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/laanwj"
   },
   "comments" : 9,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9996/comments",
   "created_at" : "2017-03-15T02:36:35Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9996/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/9996",
   "id" : 214265272,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "id" : 62963516,
         "name" : "Tests",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9996/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 9996,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "Running python tests fails",
   "updated_at" : "2017-08-24T09:08:28Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9996",
   "user" : {
      "avatar_url" : "https://avatars0.githubusercontent.com/u/3020646?v=4",
      "events_url" : "https://api.github.com/users/NicolasDorier/events{/privacy}",
      "followers_url" : "https://api.github.com/users/NicolasDorier/followers",
      "following_url" : "https://api.github.com/users/NicolasDorier/following{/other_user}",
      "gists_url" : "https://api.github.com/users/NicolasDorier/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/NicolasDorier",
      "id" : 3020646,
      "login" : "NicolasDorier",
      "organizations_url" : "https://api.github.com/users/NicolasDorier/orgs",
      "received_events_url" : "https://api.github.com/users/NicolasDorier/received_events",
      "repos_url" : "https://api.github.com/users/NicolasDorier/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/NicolasDorier/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/NicolasDorier/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/NicolasDorier"
   }
}
