{
   "assignee" : null,
   "body" : "I am building with LXC containers and I received this error while gbuild'ing qt-linux.yml:\r\n```\r\n--- Building for precise i386 ---\r\nStopping target if it is up\r\nMaking a new image copy\r\nstdin: is not a tty\r\nlxc-start: Connection refused - inotify event with no name (mask 32768)\r\nStarting target\r\nChecking if target is up\r\nPreparing build environment\r\nlxc-start: Connection refused - inotify event with no name (mask 32768)\r\nUpdating apt-get repository (log in var/install.log)\r\nInstalling additional packages (log in var/install.log)\r\nbin/gbuild:21:in `system!': failed to run on-target -u root -e DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -y install zip unzip faketime unzip libxext-dev > var/install.log 2>&1 (RuntimeError)\r\n        from bin/gbuild:87:in `build_one_configuration'\r\n        from bin/gbuild:235:in `block (2 levels) in <main>'\r\n        from bin/gbuild:230:in `each'\r\n        from bin/gbuild:230:in `block in <main>'\r\n        from bin/gbuild:228:in `each'\r\n        from bin/gbuild:228:in `<main>'\r\n```\r\n\r\nThe var/install.log file contains:\r\n```\r\nReading package lists...\r\nBuilding dependency tree...\r\nReading state information...\r\nThe following extra packages will be installed:\r\n  libpthread-stubs0 libpthread-stubs0-dev libx11-dev libxau-dev libxcb1-dev\r\n  libxdmcp-dev x11proto-core-dev x11proto-input-dev x11proto-kb-dev\r\n  x11proto-xext-dev xorg-sgml-doctools xtrans-dev\r\nSuggested packages:\r\n  libxcb-doc\r\nRecommended packages:\r\n  libx11-doc\r\nThe following NEW packages will be installed:\r\n  faketime libpthread-stubs0 libpthread-stubs0-dev libx11-dev libxau-dev\r\n  libxcb1-dev libxdmcp-dev libxext-dev unzip x11proto-core-dev\r\n  x11proto-input-dev x11proto-kb-dev x11proto-xext-dev xorg-sgml-doctools\r\n  xtrans-dev zip\r\n0 upgraded, 16 newly installed, 0 to remove and 0 not upgraded.\r\nNeed to get 2,454 kB of archives.\r\nAfter this operation, 8,441 kB of additional disk space will be used.\r\nWARNING: The following packages cannot be authenticated!\r\n  libpthread-stubs0 libpthread-stubs0-dev xorg-sgml-doctools libxau-dev\r\n  libxdmcp-dev x11proto-kb-dev xtrans-dev x11proto-xext-dev zip faketime\r\nE: There are problems and -y was used without --force-yes\r\nlxc-start: Connection refused - inotify event with no name (mask 32768)\r\n```\r\n**NOTE:** I have always ignored those errors \"lxc-start: Connection refused - inotify event with no name (mask 32768)\", because I always get them also when gbuild'ing 0.9.1, but they do not affect the end result (matching).\r\n\r\nHas somebody else experienced this issue?\r\n\r\nI am really wondering what is causing this. And I have no intention to use --force-yes.",
   "closed_at" : "2014-06-12T05:28:20Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/7117866?v=3",
      "events_url" : "https://api.github.com/users/gdm85/events{/privacy}",
      "followers_url" : "https://api.github.com/users/gdm85/followers",
      "following_url" : "https://api.github.com/users/gdm85/following{/other_user}",
      "gists_url" : "https://api.github.com/users/gdm85/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/gdm85",
      "id" : 7117866,
      "login" : "gdm85",
      "organizations_url" : "https://api.github.com/users/gdm85/orgs",
      "received_events_url" : "https://api.github.com/users/gdm85/received_events",
      "repos_url" : "https://api.github.com/users/gdm85/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/gdm85/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/gdm85/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/gdm85"
   },
   "comments" : 2,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/4324/comments",
   "created_at" : "2014-06-11T05:12:17Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/4324/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/4324",
   "id" : 35452097,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/4324/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 4324,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "gitian-build (0.9.2rc2) qt-linux.yml: error with unauthenticated packages",
   "updated_at" : "2014-06-12T05:28:20Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/4324",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/7117866?v=3",
      "events_url" : "https://api.github.com/users/gdm85/events{/privacy}",
      "followers_url" : "https://api.github.com/users/gdm85/followers",
      "following_url" : "https://api.github.com/users/gdm85/following{/other_user}",
      "gists_url" : "https://api.github.com/users/gdm85/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/gdm85",
      "id" : 7117866,
      "login" : "gdm85",
      "organizations_url" : "https://api.github.com/users/gdm85/orgs",
      "received_events_url" : "https://api.github.com/users/gdm85/received_events",
      "repos_url" : "https://api.github.com/users/gdm85/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/gdm85/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/gdm85/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/gdm85"
   }
}
