[
   {
      "_links" : {
         "html" : {
            "href" : "https://github.com/bitcoin/bitcoin/pull/10632#discussion_r122917850"
         },
         "pull_request" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/10632"
         },
         "self" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/122917850"
         }
      },
      "body" : "micronit: The other subtests are defined in the order that they're called. Perhaps place this definition after the other subtests?",
      "commit_id" : "5555fa8b74bc3c8e68232acbf4c54b9a8fadb8f2",
      "created_at" : "2017-06-20T08:59:09Z",
      "diff_hunk" : "@@ -34,14 +37,26 @@ def __init__(self):\n         super().__init__()\n         self.setup_clean_chain = False\n         self.num_nodes = 1\n+        self.extra_args = [['-stopatheight=207']]\n \n     def run_test(self):\n         self._test_getchaintxstats()\n         self._test_gettxoutsetinfo()\n         self._test_getblockheader()\n         self._test_getdifficulty()\n         self._test_getnetworkhashps()\n-        self.nodes[0].verifychain(4, 0)\n+        self._test_stopatheight()\n+        assert self.nodes[0].verifychain(4, 0)\n+\n+    def _test_stopatheight(self):",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/10632#discussion_r122917850",
      "id" : 122917850,
      "original_commit_id" : "fa75f235f14c05c7d7d433396f4f49809860340d",
      "original_position" : 33,
      "path" : "test/functional/blockchain.py",
      "position" : null,
      "pull_request_review_id" : 45072476,
      "pull_request_url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/10632",
      "updated_at" : "2017-06-20T11:35:29Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/122917850",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/1063656?v=3",
         "events_url" : "https://api.github.com/users/jnewbery/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jnewbery/followers",
         "following_url" : "https://api.github.com/users/jnewbery/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jnewbery/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jnewbery",
         "id" : 1063656,
         "login" : "jnewbery",
         "organizations_url" : "https://api.github.com/users/jnewbery/orgs",
         "received_events_url" : "https://api.github.com/users/jnewbery/received_events",
         "repos_url" : "https://api.github.com/users/jnewbery/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jnewbery/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jnewbery/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jnewbery"
      }
   },
   {
      "_links" : {
         "html" : {
            "href" : "https://github.com/bitcoin/bitcoin/pull/10632#discussion_r123657939"
         },
         "pull_request" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/10632"
         },
         "self" : {
            "href" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/123657939"
         }
      },
      "body" : "I believe this call to generate might fail -- isn't it possible the node's shutdown will interrupt the RPC response?  That looks to me like what happened here:\r\nhttps://travis-ci.org/bitcoin/bitcoin/jobs/245917226#L2275\r\n\r\nI think we should wrap the generate(1) in a try...except and allow for the RPC to fail due to connection refused, etc.",
      "commit_id" : "5555fa8b74bc3c8e68232acbf4c54b9a8fadb8f2",
      "created_at" : "2017-06-23T01:47:26Z",
      "diff_hunk" : "@@ -129,5 +134,18 @@ def _test_getnetworkhashps(self):\n         # This should be 2 hashes every 10 minutes or 1/300\n         assert abs(hashes_per_second * 300 - 1) < 0.0001\n \n+    def _test_stopatheight(self):\n+        assert_equal(self.nodes[0].getblockcount(), 200)\n+        self.nodes[0].generate(6)\n+        assert_equal(self.nodes[0].getblockcount(), 206)\n+        self.log.debug('Node should not stop at this height')\n+        assert_raises(subprocess.TimeoutExpired, lambda: bitcoind_processes[0].wait(timeout=3))\n+        self.nodes[0].generate(1)",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/10632#discussion_r123657939",
      "id" : 123657939,
      "original_commit_id" : "5555fa8b74bc3c8e68232acbf4c54b9a8fadb8f2",
      "original_position" : 45,
      "path" : "test/functional/blockchain.py",
      "position" : 45,
      "pull_request_review_id" : 45884599,
      "pull_request_url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/10632",
      "updated_at" : "2017-06-23T01:47:26Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/comments/123657939",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/7463573?v=3",
         "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sdaftuar/followers",
         "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sdaftuar",
         "id" : 7463573,
         "login" : "sdaftuar",
         "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
         "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
         "repos_url" : "https://api.github.com/users/sdaftuar/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sdaftuar"
      }
   }
]
