[
   {
      "body" : "Did it do a rescan?\r\n(hard to miss, your node would hang for some time and it prints to debug.log)",
      "created_at" : "2017-06-24T09:48:58Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-310828852",
      "id" : 310828852,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/10666",
      "updated_at" : "2017-06-24T09:48:58Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/310828852",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "body" : "Yeah, there was no rescan. I am able to reproduce by:\r\n\r\nCreate an address on bitaddress.org\r\nSend some bitcoin to that address\r\nWait until the bitcoin have got a couple of confirmations\r\nCheck the balance\r\nImport private key with false set for rescan\r\nCheck the balance, and see that it found the money",
      "created_at" : "2017-06-24T18:13:08Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-310855213",
      "id" : 310855213,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/10666",
      "updated_at" : "2017-06-24T18:13:25Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/310855213",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/20143291?v=3",
         "events_url" : "https://api.github.com/users/FrozenPrincess/events{/privacy}",
         "followers_url" : "https://api.github.com/users/FrozenPrincess/followers",
         "following_url" : "https://api.github.com/users/FrozenPrincess/following{/other_user}",
         "gists_url" : "https://api.github.com/users/FrozenPrincess/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/FrozenPrincess",
         "id" : 20143291,
         "login" : "FrozenPrincess",
         "organizations_url" : "https://api.github.com/users/FrozenPrincess/orgs",
         "received_events_url" : "https://api.github.com/users/FrozenPrincess/received_events",
         "repos_url" : "https://api.github.com/users/FrozenPrincess/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/FrozenPrincess/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/FrozenPrincess/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/FrozenPrincess"
      }
   },
   {
      "body" : "I'm also totally sure I didn't run with rescan, because if I try:\r\n\r\n`Rescan is disabled in pruned mode (code -4)`",
      "created_at" : "2017-06-24T18:15:48Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-310855452",
      "id" : 310855452,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/10666",
      "updated_at" : "2017-06-24T18:15:48Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/310855452",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/20143291?v=3",
         "events_url" : "https://api.github.com/users/FrozenPrincess/events{/privacy}",
         "followers_url" : "https://api.github.com/users/FrozenPrincess/followers",
         "following_url" : "https://api.github.com/users/FrozenPrincess/following{/other_user}",
         "gists_url" : "https://api.github.com/users/FrozenPrincess/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/FrozenPrincess",
         "id" : 20143291,
         "login" : "FrozenPrincess",
         "organizations_url" : "https://api.github.com/users/FrozenPrincess/orgs",
         "received_events_url" : "https://api.github.com/users/FrozenPrincess/received_events",
         "repos_url" : "https://api.github.com/users/FrozenPrincess/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/FrozenPrincess/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/FrozenPrincess/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/FrozenPrincess"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "i thought this is how it works as we used to set `rescan=false` when doing `importprivkeys` to save lots of time and notifications. we were able to see the coins associated with the imported privkeys instantly.\r\n\r\nbut, we just tried again using 0.14.1 and it's no longer working. The call returned w/o an error but the coins did not show up, and `validateaddress` did not even list the address as mine. Repeating the same `importprivkey` with `rescan=true` had no effect.\r\n\r\nWhat happened? What's the proper way of importing privkeys with coins in them? Really don't want the rescan as it takes too long to run and fires out duplicate notifications. Thanks",
      "created_at" : "2017-10-05T15:54:44Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-334509585",
      "id" : 334509585,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/10666",
      "updated_at" : "2017-10-05T15:54:44Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/334509585",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/25197028?v=4",
         "events_url" : "https://api.github.com/users/underst00d/events{/privacy}",
         "followers_url" : "https://api.github.com/users/underst00d/followers",
         "following_url" : "https://api.github.com/users/underst00d/following{/other_user}",
         "gists_url" : "https://api.github.com/users/underst00d/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/underst00d",
         "id" : 25197028,
         "login" : "underst00d",
         "organizations_url" : "https://api.github.com/users/underst00d/orgs",
         "received_events_url" : "https://api.github.com/users/underst00d/received_events",
         "repos_url" : "https://api.github.com/users/underst00d/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/underst00d/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/underst00d/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/underst00d"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> we were able to see the coins associated with the imported privkeys instantly.\r\n\r\nWhat made you think that would happen? The wallet only knows about your coins if it rescans the blockchain. If you don't have it rescan, then it won't know about any of your coins.\r\n\r\n> The call returned w/o an error but the coins did not show up\r\n\r\nAs is expected.\r\n\r\n> repeating the same `importprivkey` with `rescan=true` had no effect.\r\n\r\nWhat exactly is the command you are running?",
      "created_at" : "2017-10-05T16:03:57Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-334512416",
      "id" : 334512416,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/10666",
      "updated_at" : "2017-10-05T16:03:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/334512416",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/3782274?v=4",
         "events_url" : "https://api.github.com/users/achow101/events{/privacy}",
         "followers_url" : "https://api.github.com/users/achow101/followers",
         "following_url" : "https://api.github.com/users/achow101/following{/other_user}",
         "gists_url" : "https://api.github.com/users/achow101/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/achow101",
         "id" : 3782274,
         "login" : "achow101",
         "organizations_url" : "https://api.github.com/users/achow101/orgs",
         "received_events_url" : "https://api.github.com/users/achow101/received_events",
         "repos_url" : "https://api.github.com/users/achow101/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/achow101/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/achow101/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/achow101"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "i did it a few months ago (or more than 1 year) and i'm very sure the coins showed up. cannot remember the exact version number though.\r\n\r\nok then why `validateaddress` shows `ismine` as false after an error-free privkey import?\r\n\r\n`bitcoin-cli importprivkey <key> \"\" false`\r\n\r\nUPDATE:\r\n\r\nI did a` importaddress <theaddr>` to force a rescan. after a long wait, and still not seeing the coins. `ismine` is still false.\r\n\r\nToo bad it seems once an addr is added as watch only, there's no way to remove it.",
      "created_at" : "2017-10-05T16:11:52Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-334514724",
      "id" : 334514724,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/10666",
      "updated_at" : "2017-10-05T17:18:53Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/334514724",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/25197028?v=4",
         "events_url" : "https://api.github.com/users/underst00d/events{/privacy}",
         "followers_url" : "https://api.github.com/users/underst00d/followers",
         "following_url" : "https://api.github.com/users/underst00d/following{/other_user}",
         "gists_url" : "https://api.github.com/users/underst00d/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/underst00d",
         "id" : 25197028,
         "login" : "underst00d",
         "organizations_url" : "https://api.github.com/users/underst00d/orgs",
         "received_events_url" : "https://api.github.com/users/underst00d/received_events",
         "repos_url" : "https://api.github.com/users/underst00d/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/underst00d/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/underst00d/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/underst00d"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "random though: do you import an HD derived private key that uses the same seed and derivation-path than core does (maybe exported your xpriv via dumpwallet)?\r\n\r\nOr: do you have \"rescan=1\" in your bitcoin.conf?",
      "created_at" : "2017-10-07T03:44:01Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-334907847",
      "id" : 334907847,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/10666",
      "updated_at" : "2017-10-07T03:44:01Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/334907847",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/178464?v=4",
         "events_url" : "https://api.github.com/users/jonasschnelli/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonasschnelli/followers",
         "following_url" : "https://api.github.com/users/jonasschnelli/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonasschnelli",
         "id" : 178464,
         "login" : "jonasschnelli",
         "organizations_url" : "https://api.github.com/users/jonasschnelli/orgs",
         "received_events_url" : "https://api.github.com/users/jonasschnelli/received_events",
         "repos_url" : "https://api.github.com/users/jonasschnelli/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonasschnelli/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonasschnelli"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "> random though: do you import an HD derived private key that uses the same seed and derivation-path than core does (maybe exported your xpriv via dumpwallet)?\r\n\r\nNo. The issue is [easily reproducible](https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-310855213) with arbitrary addresses  \r\n\r\n> Or: do you have \"rescan=1\" in your bitcoin.conf?\r\n\r\nNope\r\n\r\n",
      "created_at" : "2017-10-07T03:49:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-334908077",
      "id" : 334908077,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/10666",
      "updated_at" : "2017-10-07T03:49:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/334908077",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/20143291?v=4",
         "events_url" : "https://api.github.com/users/FrozenPrincess/events{/privacy}",
         "followers_url" : "https://api.github.com/users/FrozenPrincess/followers",
         "following_url" : "https://api.github.com/users/FrozenPrincess/following{/other_user}",
         "gists_url" : "https://api.github.com/users/FrozenPrincess/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/FrozenPrincess",
         "id" : 20143291,
         "login" : "FrozenPrincess",
         "organizations_url" : "https://api.github.com/users/FrozenPrincess/orgs",
         "received_events_url" : "https://api.github.com/users/FrozenPrincess/received_events",
         "repos_url" : "https://api.github.com/users/FrozenPrincess/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/FrozenPrincess/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/FrozenPrincess/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/FrozenPrincess"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Transforming your description into a python test, I could not reproduce on current master:\r\n\r\n```py\r\n        # clean chain. set up nodes[1] with \"-prune=550\". Mine 101 blocks on nodes[0]\r\n\r\n        address_new = self.nodes[0].getnewaddress()\r\n        self.nodes[0].sendtoaddress(address_new, 0.1)\r\n        self.nodes[0].generate(4)\r\n        self.nodes[1].importprivkey(privkey=self.nodes[0].dumpprivkey(address_new), rescan=False)\r\n        assert self.nodes[1].getbalance() == 0",
      "created_at" : "2017-10-07T07:50:14Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-334917492",
      "id" : 334917492,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/10666",
      "updated_at" : "2017-10-07T07:50:14Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/334917492",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Did you send the coins to the new address from the wallet you are importing into? If so I'd imagine the transaction would already be 'yours' as a sent transaction in the wallet, might be the cause.\r\n\r\nEdit: indeed, a test along these lines reproduces the behaviour:\r\n```python\r\n# clean chain. set up nodes[1] with \"-prune=550\"\r\n\r\naddress_new = self.nodes[0].getnewaddress()\r\nself.nodes[1].generate(101)\r\nself.nodes[1].sendtoaddress(address_new, 49)\r\nself.nodes[1].generate(1)\r\nbalance_before = self.nodes[1].getbalance()\r\nself.nodes[1].importprivkey(privkey=self.nodes[0].dumpprivkey(address_new), rescan=False)\r\nassert self.nodes[1].getbalance() == balance_before\r\n```\r\n\r\nTest fails with nearly all 100 mature BTC left, just minus the fee for the transaction. Issue probably should be closed then",
      "created_at" : "2017-10-10T04:10:04Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-335355628",
      "id" : 335355628,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/10666",
      "updated_at" : "2017-10-10T05:12:12Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/335355628",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/3211283?v=4",
         "events_url" : "https://api.github.com/users/MeshCollider/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MeshCollider/followers",
         "following_url" : "https://api.github.com/users/MeshCollider/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MeshCollider/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MeshCollider",
         "id" : 3211283,
         "login" : "MeshCollider",
         "organizations_url" : "https://api.github.com/users/MeshCollider/orgs",
         "received_events_url" : "https://api.github.com/users/MeshCollider/received_events",
         "repos_url" : "https://api.github.com/users/MeshCollider/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MeshCollider/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MeshCollider/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MeshCollider"
      }
   }
]
